### ISSUE TITLE
applying lift migrations

### ISSUE THREAD

**Issue by priley86** [CaptainChemist/docker-prisma#2]
hi @CaptainChemist ,

can you possibly describe the process for saving and commiting migrations? I'm having troubles deploying them w/ docker. I've tried adding the following in backend package.json:
```
    "run-migrations": "prisma2 lift save",
    "apply-migrations": "prisma2 lift up",
```
and then running them from the root package.json:
```
    "run-migrations": "docker exec -it backend npm run run-migrations",
    "apply-migrations": "docker exec -it backend npm run apply-migrations",
```

It seems that when running them locally, the migration files will not get added back to the source. This will make deploying them difficult. Any ideas for this?

I've forked this repo and added DigOcean deployment steps and am currently adding the `graphql-shield` example for auth. This will require a schema change...but this is more just a question about migrations in general w/ this setup.

My fork of this repo is here...but i haven't tried commiting this yet.
https://github.com/priley86/how-to-graphql

Thanks for any advice! 👏

**Comment by priley86** [comment]
seems i am hitting this issue at the moment: https://github.com/prisma/lift/issues/25... but i think the question about saving migrations via Docker is still a good one. Maybe adjusting the `volume` in docker-compose can work can it saves locally some way?

**Comment by priley86** [comment]
Running the above from the root is not necessary. Migrations will work if you run `prisma2 lift save` prior to running `prisma2 lift up`. This will write an initial migration and then subsequent migrations will work correctly. 

The connection string you have here should still work locally (so it's not advised to run the migration inside docker) so that migration files will save in git in the `prisma` folder. But if you are attempting to run `npm run prisma2 dev` (outside of docker), you'd want a connection string like this:

```
url = "mysql://root:prisma@localhost:3306/prisma"
```

However, `prisma2 dev` is currently broken regarding migrations. Noted that in the issue above and the one here:
https://github.com/prisma/prisma2/issues/37

Holding from using `prisma2 dev` 's auto migration feature for now...

Bummer 😢

**Comment by CaptainChemist** [comment]
Hey @priley86 I'm working on a blog post that will address how to deploy this stack serverlessly using zeit's now service so stay tuned for that. To get you started though with prod deployments, you can replace the url string with `env("YOUR_ENV_VARIABLE")` and as long as the environmental variable is exported in your bash shell it will inject it there. This can be a way to switch environments because you are right that storing the migrations inside a docker container is not a smart move since containers are so ephemeral. 

My approach to a remote database would be use `prisma2 dev` after setting the url to your remote database and migrating it that way initially or using your `prisma2 lift save` and `prisma2 lift up` like you say. 

Thanks for pointing out that the `prisma2 dev` is broken with migrations- I didn't know that but I also didn't think to test that out.

Thanks so much for the thoughtful comments! It sounds like you answered your own questions right? If there is something I missed just ping me. 

I really like that you are doing graphql-shield by the way. That's on my radar to add in the future as well. :)

**Comment by priley86** [comment]
thanks a lot @CaptainChemist ! I've taken a stab at adding `graphql-shield` to your template... it _mostly_ works:
https://github.com/priley86/how-to-graphql/commits/master

Still waiting on the [issue](https://github.com/maticzav/graphql-shield/issues/361) referenced in the prisma2 examples for adding the middleware, but this essentially works like you'd expect now...

Happy to get your feedback on this once you have a chance to try it! Have really been enjoying this template.
